import type { Appointment, ClinicWing, Delay, Doctor, Queue } from './adminService';

export function getTodayDateString(offsetDays = 0): string {
  const d = new Date();
  if (offsetDays !== 0) {
    d.setDate(d.getDate() + offsetDays);
  }
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Amanda Silva',
    department: 'General OPD',
    hospital: 'Colombo National Hospital',
    room: 'Room 12',
    maxTokens: 45,
    consultingSlots: ['08:30 AM - 12:00 PM', '01:30 PM - 04:30 PM'],
    consultingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    active: true,
  },
  {
    id: 'doc-2',
    name: 'Dr. Rohan Perera',
    department: 'General OPD',
    hospital: 'Colombo National Hospital',
    room: 'Room 14',
    maxTokens: 40,
    consultingSlots: ['08:30 AM - 12:30 PM'],
    consultingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    active: true,
  },
  {
    id: 'doc-3',
    name: 'Dr. Priyantha Silva',
    department: 'Cardiology',
    hospital: 'Colombo National Hospital',
    room: 'Room 04',
    maxTokens: 35,
    consultingSlots: ['09:00 AM - 01:00 PM', '03:00 PM - 06:00 PM'],
    consultingDays: ['Mon', 'Wed', 'Fri'],
    active: true,
  },
  {
    id: 'doc-4',
    name: 'Dr. Kanchana Jayawardena',
    department: 'Cardiology',
    hospital: 'Colombo National Hospital',
    room: 'Room 06',
    maxTokens: 30,
    consultingSlots: ['08:00 AM - 12:00 PM'],
    consultingDays: ['Tue', 'Thu', 'Sat'],
    active: true,
  },
  {
    id: 'doc-5',
    name: 'Dr. Niluka Senaratne',
    department: 'Dental',
    hospital: 'Colombo National Hospital',
    room: 'Room 21',
    maxTokens: 25,
    consultingSlots: ['09:00 AM - 01:30 PM'],
    consultingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    active: true,
  },
  {
    id: 'doc-6',
    name: 'Dr. Kamal Fernando',
    department: 'Dental',
    hospital: 'Colombo National Hospital',
    room: 'Room 22',
    maxTokens: 28,
    consultingSlots: ['01:00 PM - 05:00 PM'],
    consultingDays: ['Mon', 'Wed', 'Fri', 'Sat'],
    active: true,
  },
  {
    id: 'doc-7',
    name: 'Dr. Anoma Wijesinghe',
    department: 'Eye OPD',
    hospital: 'Colombo National Hospital',
    room: 'Room 08',
    maxTokens: 35,
    consultingSlots: ['08:30 AM - 12:30 PM'],
    consultingDays: ['Mon', 'Tue', 'Thu', 'Fri'],
    active: true,
  },
  {
    id: 'doc-8',
    name: 'Dr. Suneth Bandara',
    department: 'Orthopedics',
    hospital: 'Colombo National Hospital',
    room: 'Room 18',
    maxTokens: 30,
    consultingSlots: ['09:00 AM - 02:00 PM'],
    consultingDays: ['Tue', 'Wed', 'Thu', 'Sat'],
    active: true,
  },
];

export const INITIAL_CLINIC_WINGS: ClinicWing[] = [
  {
    id: 'wing-1',
    name: 'General OPD Unit 1',
    building: 'Outpatient Complex B',
    floor: 'Ground Floor',
    rooms: 'Rooms 11 - 16',
    maxDailyTokens: 120,
    clinicHead: 'Dr. Amanda Silva',
    operatingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    active: true,
  },
  {
    id: 'wing-2',
    name: 'Cardiology Wing A',
    building: 'Main Hospital Tower A',
    floor: '2nd Floor',
    rooms: 'Rooms 01 - 06',
    maxDailyTokens: 70,
    clinicHead: 'Dr. Priyantha Silva',
    operatingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    active: true,
  },
  {
    id: 'wing-3',
    name: 'Dental Clinic Suite',
    building: 'Dental Health Institute',
    floor: '1st Floor',
    rooms: 'Rooms 21 - 25',
    maxDailyTokens: 60,
    clinicHead: 'Dr. Niluka Senaratne',
    operatingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    active: true,
  },
  {
    id: 'wing-4',
    name: 'ENT Special Care Wing',
    building: 'Specialized Clinics Wing',
    floor: '3rd Floor',
    rooms: 'Rooms 07 - 10',
    maxDailyTokens: 50,
    clinicHead: 'Dr. Anoma Wijesinghe',
    operatingDays: ['Mon', 'Tue', 'Thu', 'Fri'],
    active: true,
  },
  {
    id: 'wing-5',
    name: 'Orthopedics & Trauma Center',
    building: 'Surgical & Ortho Complex',
    floor: 'Ground Floor',
    rooms: 'Rooms 17 - 20',
    maxDailyTokens: 60,
    clinicHead: 'Dr. Suneth Bandara',
    operatingDays: ['Tue', 'Wed', 'Thu', 'Sat'],
    active: true,
  },
];

export function getInitialQueues(): Queue[] {
  const today = getTodayDateString();
  return [
    {
      id: 'queue-1',
      doctorId: 'doc-1',
      date: today,
      currentToken: 0,
      nextTokenNumber: 1,
      nextPatientName: 'Kasun Fernando',
      status: 'active',
      delayMinutes: 0,
    },
    {
      id: 'queue-2',
      doctorId: 'doc-2',
      date: today,
      currentToken: 8,
      nextTokenNumber: 9,
      nextPatientName: 'Chathurika Madushani',
      status: 'delayed',
      delayMinutes: 20,
    },
    {
      id: 'queue-3',
      doctorId: 'doc-3',
      date: today,
      currentToken: 11,
      nextTokenNumber: 12,
      nextPatientName: 'Nimal Gunawardena',
      status: 'active',
      delayMinutes: 0,
    },
    {
      id: 'queue-4',
      doctorId: 'doc-4',
      date: today,
      currentToken: 0,
      nextTokenNumber: 1,
      nextPatientName: 'Sachini Dissanayake',
      status: 'upcoming',
      delayMinutes: 0,
    },
    {
      id: 'queue-5',
      doctorId: 'doc-5',
      date: today,
      currentToken: 6,
      nextTokenNumber: 7,
      nextPatientName: 'Thilina Ranasinghe',
      status: 'break',
      delayMinutes: 0,
    },
    {
      id: 'queue-6',
      doctorId: 'doc-6',
      date: today,
      currentToken: 10,
      nextTokenNumber: 11,
      nextPatientName: 'Hashini Wickramasinghe',
      status: 'active',
      delayMinutes: 0,
    },
    {
      id: 'queue-7',
      doctorId: 'doc-7',
      date: today,
      currentToken: 4,
      nextTokenNumber: 5,
      nextPatientName: 'Nuwan Kulasekara',
      status: 'delayed',
      delayMinutes: 15,
    },
    {
      id: 'queue-8',
      doctorId: 'doc-8',
      date: today,
      currentToken: 0,
      nextTokenNumber: 1,
      nextPatientName: 'Saman Kumara',
      status: 'upcoming',
      delayMinutes: 0,
    },
  ];
}

export function getInitialAppointments(): Appointment[] {
  const today = getTodayDateString(0);
  const tomorrow = getTodayDateString(1);
  const inTwoDays = getTodayDateString(2);
  const inThreeDays = getTodayDateString(3);

  return [
    // ── TODAY ─────────────────────────────────────────────────────────────
    {
      id: 'appt-1',
      patientId: 'pat-1042',
      patientName: 'Kasun Fernando',
      patientPhone: '+94 77 234 5678',
      patientCode: 'PT-2026-1042',
      doctorId: 'doc-1',
      doctorName: 'Dr. Amanda Silva',
      department: 'General OPD',
      slotId: 'slot-1',
      date: today,
      time: '09:45 AM',
      endTime: '10:00 AM',
      status: 'upcoming',
      tokenNumber: 1,
      bookingType: 'Online App Booking',
      waitingInfo: 'Waiting in OPD Lobby A • Next in queue',
    },
    {
      id: 'appt-2',
      patientId: 'pat-1038',
      patientName: 'Kavindu Jayasuriya',
      patientPhone: '+94 71 890 1234',
      patientCode: 'PT-2026-1038',
      doctorId: 'doc-1',
      doctorName: 'Dr. Amanda Silva',
      department: 'General OPD',
      slotId: 'slot-1',
      date: today,
      time: '10:00 AM',
      endTime: '10:15 AM',
      status: 'upcoming',
      tokenNumber: 2,
      bookingType: 'Online App Booking',
      waitingInfo: 'Second patient in the General OPD queue',
    },
    {
      id: 'appt-3',
      patientId: 'pat-1055',
      patientName: 'Chathurika Madushani',
      patientPhone: '+94 76 543 2198',
      patientCode: 'PT-2026-1055',
      doctorId: 'doc-2',
      doctorName: 'Dr. Rohan Perera',
      department: 'General OPD',
      slotId: 'slot-2',
      date: today,
      time: '10:15 AM',
      endTime: '10:30 AM',
      status: 'upcoming',
      tokenNumber: 9,
      bookingType: 'Counter Pre-booked',
      waitingInfo: 'Delay broadcast received (+20m)',
    },
    {
      id: 'appt-4',
      patientId: 'pat-0981',
      patientName: 'Nimal Gunawardena',
      patientPhone: '+94 70 334 1122',
      patientCode: 'PT-2026-0981',
      doctorId: 'doc-3',
      doctorName: 'Dr. Priyantha Silva',
      department: 'Cardiology',
      slotId: 'slot-3',
      date: today,
      time: '10:30 AM',
      endTime: '10:50 AM',
      status: 'upcoming',
      tokenNumber: 12,
      bookingType: 'Online App Booking',
      waitingInfo: 'ECG vitals verified • Waiting Rm 04',
    },
    {
      id: 'appt-5',
      patientId: 'pat-0975',
      patientName: 'Malini Fonseka',
      patientPhone: '+94 77 445 6677',
      patientCode: 'PT-2026-0975',
      doctorId: 'doc-3',
      doctorName: 'Dr. Priyantha Silva',
      department: 'Cardiology',
      slotId: 'slot-3',
      date: today,
      time: '09:50 AM',
      endTime: '10:10 AM',
      status: 'completed',
      tokenNumber: 10,
      bookingType: 'Counter Pre-booked',
      waitingInfo: 'Medication prescribed',
    },
    {
      id: 'appt-6',
      patientId: 'pat-1102',
      patientName: 'Thilina Ranasinghe',
      patientPhone: '+94 75 112 3344',
      patientCode: 'PT-2026-1102',
      doctorId: 'doc-5',
      doctorName: 'Dr. Niluka Senaratne',
      department: 'Dental',
      slotId: 'slot-5',
      date: today,
      time: '11:00 AM',
      endTime: '11:30 AM',
      status: 'upcoming',
      tokenNumber: 7,
      bookingType: 'Online App Booking',
      waitingInfo: 'Doctor on brief break (until 11:15)',
    },
    {
      id: 'appt-7',
      patientId: 'pat-1120',
      patientName: 'Nuwan Kulasekara',
      patientPhone: '+94 78 889 9900',
      patientCode: 'PT-2026-1120',
      doctorId: 'doc-7',
      doctorName: 'Dr. Anoma Wijesinghe',
      department: 'Eye OPD',
      slotId: 'slot-7',
      date: today,
      time: '11:15 AM',
      endTime: '11:35 AM',
      status: 'upcoming',
      tokenNumber: 5,
      bookingType: 'Online App Booking',
      waitingInfo: 'Delay broadcast received (+15m)',
    },

    // ── TOMORROW ──────────────────────────────────────────────────────────
    {
      id: 'appt-8',
      patientId: 'pat-1144',
      patientName: 'Duminda Silva',
      patientPhone: '+94 77 654 3210',
      patientCode: 'PT-2026-1144',
      doctorId: 'doc-1',
      doctorName: 'Dr. Amanda Silva',
      department: 'General OPD',
      slotId: 'slot-1',
      date: tomorrow,
      time: '08:30 AM',
      endTime: '08:45 AM',
      status: 'upcoming',
      tokenNumber: 1,
      bookingType: 'Online App Booking',
      waitingInfo: 'Morning opening slot',
    },
    {
      id: 'appt-9',
      patientId: 'pat-1150',
      patientName: 'Sachini Dissanayake',
      patientPhone: '+94 71 223 3445',
      patientCode: 'PT-2026-1150',
      doctorId: 'doc-4',
      doctorName: 'Dr. Kanchana Jayawardena',
      department: 'Cardiology',
      slotId: 'slot-4',
      date: tomorrow,
      time: '08:00 AM',
      endTime: '08:20 AM',
      status: 'upcoming',
      tokenNumber: 1,
      bookingType: 'Online App Booking',
      waitingInfo: 'Fasting blood sugar test ready',
    },
    {
      id: 'appt-10',
      patientId: 'pat-1162',
      patientName: 'Hashini Wickramasinghe',
      patientPhone: '+94 72 334 5566',
      patientCode: 'PT-2026-1162',
      doctorId: 'doc-6',
      doctorName: 'Dr. Kamal Fernando',
      department: 'Dental',
      slotId: 'slot-6',
      date: tomorrow,
      time: '01:30 PM',
      endTime: '02:00 PM',
      status: 'upcoming',
      tokenNumber: 2,
      bookingType: 'Counter Pre-booked',
      waitingInfo: 'Dental checkup & cleaning',
    },
    {
      id: 'appt-11',
      patientId: 'pat-1175',
      patientName: 'Saman Kumara',
      patientPhone: '+94 77 778 8899',
      patientCode: 'PT-2026-1175',
      doctorId: 'doc-8',
      doctorName: 'Dr. Suneth Bandara',
      department: 'Orthopedics',
      slotId: 'slot-8',
      date: tomorrow,
      time: '09:30 AM',
      endTime: '09:50 AM',
      status: 'upcoming',
      tokenNumber: 3,
      bookingType: 'Online App Booking',
      waitingInfo: 'Post-surgery follow-up',
    },

    // ── UPCOMING ──────────────────────────────────────────────────────────
    {
      id: 'appt-12',
      patientId: 'pat-1201',
      patientName: 'Ruwan Pathirana',
      patientPhone: '+94 77 990 0112',
      patientCode: 'PT-2026-1201',
      doctorId: 'doc-3',
      doctorName: 'Dr. Priyantha Silva',
      department: 'Cardiology',
      slotId: 'slot-3',
      date: inTwoDays,
      time: '09:40 AM',
      endTime: '10:00 AM',
      status: 'upcoming',
      tokenNumber: 5,
      bookingType: 'Online App Booking',
      waitingInfo: 'Stress test appointment',
    },
    {
      id: 'appt-13',
      patientId: 'pat-1215',
      patientName: 'Anula Ratnayake',
      patientPhone: '+94 71 556 7788',
      patientCode: 'PT-2026-1215',
      doctorId: 'doc-1',
      doctorName: 'Dr. Amanda Silva',
      department: 'General OPD',
      slotId: 'slot-1',
      date: inThreeDays,
      time: '10:00 AM',
      endTime: '10:15 AM',
      status: 'upcoming',
      tokenNumber: 8,
      bookingType: 'Counter Pre-booked',
      waitingInfo: 'Routine health screen',
    },
  ];
}

export const INITIAL_DELAYS: Delay[] = [
  {
    id: 'delay-1',
    doctorId: 'doc-2',
    doctorName: 'Dr. Rohan Perera',
    message: 'Doctor is attending an emergency consultation. Session delayed by 20 minutes.',
    minutes: 20,
  },
  {
    id: 'delay-2',
    doctorId: 'doc-7',
    doctorName: 'Dr. Anoma Wijesinghe',
    message: 'Dr. Anoma Wijesinghe session is delayed by 15 minutes due to theater procedure.',
    minutes: 15,
  },
];
